name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Choose the version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if on main branch
        run: |
          if [[ "$(git rev-parse --abbrev-ref HEAD)" != "main" ]]; then
            echo "This workflow can only run on the 'main' branch."
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set Git user identity (repository-scoped)
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions Bot"

      - name: Check if 'release' branch exists
        run: |
          if git show-ref --verify --quiet refs/heads/release; then
            echo "Release branch already exists, exiting."
            exit 1
          fi

      - name: Create and switch to release branch
        run: |
          git checkout -b release
          git push origin release

      - name: Instal PIP requirements
        run: |
          pip install bump2version

      - name: Bump version
        run: |
          version_type="${{ github.event.inputs.version }}"
          echo "Bumping version by: $version_type"
          bump2version $version_type
          git push --follow-tags

      - name: Create Pull Request for Release
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Release Version"
          body: "This PR includes the bumped version and tag."
          head: release  # Source branch
          base: main     # Target branch
          github_token: ${{ secrets.GITHUB_TOKEN }}
