name: Deploy Release

on:
  pull_request:
    types: [closed]  # Trigger when the PR is closed (merged or closed without merging)
    branches:
      - main
    # Make sure the source branch is 'release'
    if: github.event.pull_request.head.ref == 'release'

permissions:
  contents: write
  packages: write

jobs:
  deploy-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set Git user identity (repository-scoped)
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions Bot"

      - name: Get Version
        run: |
          # Capture the bumped version from .bumpversion.cfg
          bumped_version=$(grep -oP '(?<=current_version = ).*' .bumpversion.cfg)
          echo "Bumped version is: $bumped_version"
          echo "VERSION=$bumped_version" >> $GITHUB_ENV  # Set the version as an environment variable

      - name: Download Release
        run: |
          VERSION="${{ env.VERSION }}"
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh release list
          gh release download "v$VERSION" --pattern "*" --dir dist/
          gh release edit "v$VERSION" --prerelease=false

      - name: Install PIP Requirements
        run: |
          pip install twine

      - name: Publish to PyPI
        run: |
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

      - name: Tag release in main
        run: |
          VERSION="${{ env.VERSION }}"
          # Create a new Git tag based on the version
          git tag -a "v$VERSION" -m "Release version ${{ env.VERSION }}"  
          # Push the tag to the remote repository
          git push origin "v$VERSION"
