name: publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Choose the version bump type'
        required: true
        default: 'patch'  # Default to 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install bump2version
          pip install poetry
          pip install twine

      - name: Bump version
        id: bump_version
        run: |
          version_type="${{ github.event.inputs.version }}"  # Get the chosen version type
          echo "Bumping version by: $version_type"

          # Bump version using bump2version based on the input choice
          bump2version $version_type  # This will bump patch, minor, or major based on the input
          git push --follow-tags

      - name: Build the package
        run: |
          poetry build

      - name: Publish to PyPI
        run: |
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
