name: publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Choose the version bump type'
        required: true
        default: 'patch'  # Default to 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          
permissions:
  contents: write

jobs:

  checkout:
    uses: ./.github/workflows/checkout.yml
    with:
      python_version: '3.12'
    type: workflow

  version:
    runs-on: ubuntu-latest
    needs: checkout
    steps:  
      - name: Install bump2version
        run: |
          pip install bump2version
      - name: Bump version
        id: bump_version
        run: |
          version_type="${{ github.event.inputs.version }}"  # Get the chosen version type
          echo "Bumping version by: $version_type"

          # Bump version using bump2version based on the input choice
          bump2version $version_type  # This will bump patch, minor, or major based on the input
          git push --follow-tags

  build:
    runs-on: ubuntu-latest
    needs: version
    steps:  
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -  # Install Poetry

      - name: Build the package
        run: |
          poetry build

  upload:
      runs-on: ubuntu-latest
      needs: build
      steps:  
      - name: Install Twine
        run: |
          pip install twine

      - name: Publish to PyPI
        run: |
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
