name: Create Release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  get-changes:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Release Notes
        run: |
          # Get the last version tag in the format vX.Y.Z
          LAST_TAG=$(git tag -l "v*" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          echo "LAST TAG: $LAST_TAG"
          if [ -z "$LAST_TAG" ]; then
            # If no tag is found, use the full commit log
            echo "No version tag found, using full commit log"
            git log --pretty=format:'- %s' > release_notes.md
          else
            # If a tag is found, generate release notes from the tag
            echo "Generating release notes from tag $LAST_TAG"
            git log --pretty=format:'- %s' $LAST_TAG..HEAD > release_notes.md
          fi